### ISSUE TITLE
the addon doesn't work...

### ISSUE THREAD

**Issue by boaz3d** [alextsui05/blender-off-addon#23]
hi there
thanks a lot for the addon.
unfortunateley it doen's work (not the import neither the export).
this is the massage i get (i have no idea what it means...)
any ideas? (i try with the latest blender version)
thank you anyway!

the log:
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\import_off.py", line 157, in execute
    global_matrix = axis_conversion(to_forward=self.axis_forward,
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy_extras\io_utils.py", line 301, in axis_conversion
    if from_forward[-1] == from_up[-1] or to_forward[-1] == to_up[-1]:
TypeError: '_PropertyDeferred' object is not subscriptable

location: <unknown location>:-1

**Comment by richard-sim** [comment]
I have a fork of this repo that I've updated to work with 2.91+ and 3.0+ (tested in 2.93.8 and 3.4.1), and merged in some other forks in too, to make a G.O.A.T. fork: [https://github.com/richard-sim/blender-off-addon](https://github.com/richard-sim/blender-off-addon)

Perhaps the original author @alextsui05 could either pull those changes into this repo, or redirect to the fork (there are so many forks, it's hard to find the right one - hence creating the GOAT fork).

**Comment by FlurinArner** [comment]
I can confirm that @richard-sim's [fork](https://github.com/richard-sim/blender-off-addon) worked also for me in Blender 4.5 LTS.
